services:
  
  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    environment: 
      - MYSQL_ROOT_PASSWORD=Admin@123
      - MYSQL_DATABASE=Sapphire_Dev
    ports:
      - 3306:3306
    expose:
      - 3306
    container_name: mysql

  api:
    image: sapphire-api:debug
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=DockerMySql
    command: bash -c "sleep 15 && dotnet /var/www/app/publish/SapphireApi.dll"
    expose: 
      - 80 
      - 443 
    ports:
      - 80:80
      - 443:443
    links:
      - mysql
    depends_on:
      - mysql