FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine as builder
RUN dotnet dev-certs https --clean
RUN dotnet dev-certs https --trust -ep /https/aspnetapp.pfx -p password
COPY SapphireApi /var/www
WORKDIR /var/www
RUN dotnet publish -c Relase -o /var/www/app/publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine as final
WORKDIR /var/www/app/publish
RUN apk add icu-libs
COPY --from=builder  /https/aspnetapp.pfx /https/aspnetapp.pfx 
COPY --from=builder /var/www/app/publish . 