FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine
RUN dotnet dev-certs https --clean
RUN dotnet dev-certs https --trust -ep /https/aspnetapp.pfx -p password
WORKDIR /var/www/SapphireApi/
COPY ./SapphireApi .
