FROM mcr.microsoft.com/dotnet/sdk:5.0 as builder
WORKDIR /var/www
COPY ./docker-entrypoint.debug.sh .
COPY SapphireApi .
RUN dotnet publish -c Relase -o /var/www/app/publish
WORKDIR /var/www/app/publish
RUN dotnet dev-certs https --clean
RUN dotnet dev-certs https --clean; dotnet dev-certs https --trust
